-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.anak_pasien
(
    id bigserial NOT NULL,
    nifas_id bigint,
    anak_ke integer NOT NULL,
    tanggal_lahir date NOT NULL,
    jenis_kelamin character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nama_anak character varying(255) COLLATE pg_catalog."default" NOT NULL,
    usia_kehamilan_saat_lahir character varying(255) COLLATE pg_catalog."default" NOT NULL,
    berat_lahir_anak numeric(8, 2) NOT NULL,
    panjang_lahir_anak numeric(8, 2) NOT NULL,
    lingkar_kepala_anak numeric(8, 2) NOT NULL,
    memiliki_buku_kia boolean NOT NULL DEFAULT false,
    buku_kia_bayi_kecil boolean NOT NULL DEFAULT false,
    imd boolean NOT NULL DEFAULT false,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    kondisi_ibu character varying(255) COLLATE pg_catalog."default",
    catatan_kondisi_ibu text COLLATE pg_catalog."default",
    riwayat_penyakit json,
    keterangan_masalah_lain text COLLATE pg_catalog."default",
    nifas_bidan_id bigint,
    CONSTRAINT anak_pasien_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bidans
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    nomor_izin_praktek character varying(255) COLLATE pg_catalog."default" NOT NULL,
    puskesmas_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT bidans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cache
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.cache_locks
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    owner character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_locks_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.cache_tables
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_tables_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.failed_jobs
(
    id bigserial NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT failed_jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jawaban_kuisioners
(
    id bigserial NOT NULL,
    kuisioner_id bigint NOT NULL,
    jawaban boolean NOT NULL DEFAULT false,
    jawaban_lainnya character varying(255) COLLATE pg_catalog."default",
    skrining_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT jawaban_kuisioners_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.job_batches
(
    id bigserial NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT job_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.kf
(
    id bigserial NOT NULL,
    id_nifas bigint NOT NULL,
    id_anak bigint NOT NULL,
    kunjungan_nifas_ke bigint NOT NULL,
    tanggal_kunjungan date NOT NULL DEFAULT '2025-11-02'::date,
    sbp bigint NOT NULL,
    dbp bigint NOT NULL,
    map bigint NOT NULL,
    keadaan_umum character varying(255) COLLATE pg_catalog."default",
    tanda_bahaya character varying(255) COLLATE pg_catalog."default",
    kesimpulan_pantauan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT kf_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.kf_kunjungans
(
    id bigserial NOT NULL,
    pasien_nifas_id bigint NOT NULL,
    jenis_kf character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tanggal_kunjungan date NOT NULL,
    sbp integer,
    dbp integer,
    map integer,
    keadaan_umum text COLLATE pg_catalog."default",
    tanda_bahaya text COLLATE pg_catalog."default",
    kesimpulan_pantauan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    catatan text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT kf_kunjungans_pkey PRIMARY KEY (id),
    CONSTRAINT kf_kunjungans_pasien_nifas_id_jenis_kf_unique UNIQUE (pasien_nifas_id, jenis_kf)
);

COMMENT ON COLUMN public.kf_kunjungans.sbp
    IS 'Systolic Blood Pressure (mmHg)';

COMMENT ON COLUMN public.kf_kunjungans.dbp
    IS 'Diastolic Blood Pressure (mmHg)';

COMMENT ON COLUMN public.kf_kunjungans.map
    IS 'Mean Arterial Pressure (mmHg)';

CREATE TABLE IF NOT EXISTS public.kondisi_kesehatans
(
    id bigserial NOT NULL,
    skrining_id bigint NOT NULL,
    tinggi_badan integer NOT NULL,
    berat_badan_saat_hamil numeric(5, 2) NOT NULL,
    imt double precision NOT NULL,
    status_imt character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hpht date,
    tanggal_skrining date NOT NULL,
    usia_kehamilan integer NOT NULL,
    tanggal_perkiraan_persalinan date NOT NULL,
    anjuran_kenaikan_bb character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sdp integer NOT NULL DEFAULT 0,
    dbp integer NOT NULL DEFAULT 0,
    map numeric(5, 2) NOT NULL DEFAULT '0'::numeric,
    pemeriksaan_protein_urine character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Belum dilakukan Pemeriksaan'::character varying,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT kondisi_kesehatans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.kuisioner_pasiens
(
    id bigserial NOT NULL,
    nama_pertanyaan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status_soal character varying(255) COLLATE pg_catalog."default" NOT NULL,
    resiko character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT kuisioner_pasiens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    migration character varying(255) COLLATE pg_catalog."default" NOT NULL,
    batch integer NOT NULL,
    CONSTRAINT migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pasien_nifas_bidan
(
    id bigserial NOT NULL,
    bidan_id bigint NOT NULL,
    pasien_id bigint NOT NULL,
    tanggal_mulai_nifas date,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT pasien_nifas_bidan_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pasien_nifas_rs
(
    id bigserial NOT NULL,
    rs_id bigint NOT NULL,
    pasien_id bigint NOT NULL,
    tanggal_mulai_nifas date,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    tanggal_melahirkan date,
    kf1_tanggal timestamp(0) without time zone,
    kf1_catatan text COLLATE pg_catalog."default",
    kf2_tanggal timestamp(0) without time zone,
    kf2_catatan text COLLATE pg_catalog."default",
    kf3_tanggal timestamp(0) without time zone,
    kf3_catatan text COLLATE pg_catalog."default",
    kf1_id bigint,
    kf2_id bigint,
    kf3_id bigint,
    CONSTRAINT pasien_nifas_rs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pasiens
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    nik character varying(16) COLLATE pg_catalog."default" NOT NULL,
    tempat_lahir character varying(50) COLLATE pg_catalog."default",
    tanggal_lahir date,
    status_perkawinan boolean,
    "PKecamatan" character varying(255) COLLATE pg_catalog."default",
    "PKabupaten" character varying(255) COLLATE pg_catalog."default",
    "PProvinsi" character varying(255) COLLATE pg_catalog."default",
    "PPelayanan" character varying(255) COLLATE pg_catalog."default",
    "PKarakteristik" character varying(255) COLLATE pg_catalog."default",
    "PWilayah" character varying(255) COLLATE pg_catalog."default",
    kode_pos character varying(10) COLLATE pg_catalog."default",
    rt character varying(255) COLLATE pg_catalog."default",
    rw character varying(255) COLLATE pg_catalog."default",
    pekerjaan character varying(50) COLLATE pg_catalog."default",
    pendidikan character varying(20) COLLATE pg_catalog."default",
    pembiayaan_kesehatan character varying(255) COLLATE pg_catalog."default",
    golongan_darah character varying(255) COLLATE pg_catalog."default",
    no_jkn character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT pasiens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.puskesmas
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    nama_puskesmas character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lokasi text COLLATE pg_catalog."default" NOT NULL,
    kecamatan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_mandiri boolean NOT NULL DEFAULT false,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT puskesmas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resep_obats
(
    id bigserial NOT NULL,
    rujukan_rs_id bigint NOT NULL,
    resep_obat character varying(255) COLLATE pg_catalog."default",
    dosis character varying(255) COLLATE pg_catalog."default",
    penggunaan character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    riwayat_rujukan_id bigint,
    CONSTRAINT resep_obats_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.riwayat_kehamilan_gpas
(
    id bigserial NOT NULL,
    skrining_id bigint NOT NULL,
    pasien_id bigint NOT NULL,
    total_kehamilan character varying(255) COLLATE pg_catalog."default",
    total_persalinan character varying(255) COLLATE pg_catalog."default",
    total_abortus character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT riwayat_kehamilan_gpas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.riwayat_kehamilans
(
    id bigserial NOT NULL,
    skrining_id bigint NOT NULL,
    pasien_id bigint NOT NULL,
    kehamilan integer NOT NULL,
    tahun_kehamilan integer NOT NULL,
    pengalaman_kehamilan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    berat_lahir numeric(5, 2),
    kondisi_bayi character varying(255) COLLATE pg_catalog."default",
    jenis_persalinan character varying(255) COLLATE pg_catalog."default",
    penolong_persalinan character varying(255) COLLATE pg_catalog."default",
    komplikasi character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Tidak Ada'::character varying,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT riwayat_kehamilans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.riwayat_penyakit_nifas
(
    id bigserial NOT NULL,
    nifas_id bigint NOT NULL,
    anak_pasien_id bigint NOT NULL,
    nama_penyakit character varying(255) COLLATE pg_catalog."default",
    keterangan_penyakit_lain text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT riwayat_penyakit_nifas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.riwayat_rujukans
(
    id bigserial NOT NULL,
    rujukan_id bigint NOT NULL,
    skrining_id bigint NOT NULL,
    tanggal_datang date,
    tekanan_darah character varying(255) COLLATE pg_catalog."default",
    anjuran_kontrol character varying(255) COLLATE pg_catalog."default",
    kunjungan_berikutnya character varying(255) COLLATE pg_catalog."default",
    tindakan character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    catatan text COLLATE pg_catalog."default",
    CONSTRAINT riwayat_rujukans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigserial NOT NULL,
    nama_role character varying(40) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rujukan_nifas
(
    id bigserial NOT NULL,
    id_kf bigint NOT NULL,
    rs_id bigint NOT NULL,
    status_rujukan boolean NOT NULL,
    tanggal_rujukan date NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT rujukan_nifas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rujukan_rs
(
    id bigserial NOT NULL,
    pasien_id bigint NOT NULL,
    rs_id bigint NOT NULL,
    skrining_id bigint NOT NULL,
    done_status boolean NOT NULL DEFAULT false,
    catatan_rujukan text COLLATE pg_catalog."default",
    is_rujuk boolean,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    pasien_datang boolean,
    riwayat_tekanan_darah text COLLATE pg_catalog."default",
    hasil_protein_urin text COLLATE pg_catalog."default",
    perlu_pemeriksaan_lanjut boolean,
    CONSTRAINT rujukan_rs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rumah_sakits
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    nama character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lokasi character varying(255) COLLATE pg_catalog."default" NOT NULL,
    kecamatan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    kelurahan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT rumah_sakits_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    payload text COLLATE pg_catalog."default" NOT NULL,
    last_activity integer NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.skrinings
(
    id bigserial NOT NULL,
    pasien_id bigint NOT NULL,
    puskesmas_id bigint NOT NULL,
    status_pre_eklampsia character varying(255) COLLATE pg_catalog."default",
    jumlah_resiko_sedang integer,
    jumlah_resiko_tinggi integer,
    kesimpulan character varying(255) COLLATE pg_catalog."default",
    step_form integer,
    tindak_lanjut boolean NOT NULL DEFAULT false,
    checked_status boolean NOT NULL DEFAULT false,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT skrinings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    photo character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    status boolean NOT NULL DEFAULT false,
    role_id bigint NOT NULL,
    remember_token character varying(100) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.wilayah_kerja
(
    id bigserial NOT NULL,
    nama_wilayah character varying(255) COLLATE pg_catalog."default" NOT NULL,
    puskesmas_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT wilayah_kerja_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.anak_pasien
    ADD CONSTRAINT anak_pasien_nifas_bidan_id_foreign FOREIGN KEY (nifas_bidan_id)
    REFERENCES public.pasien_nifas_bidan (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.anak_pasien
    ADD CONSTRAINT anak_pasien_nifas_id_foreign FOREIGN KEY (nifas_id)
    REFERENCES public.pasien_nifas_rs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bidans
    ADD CONSTRAINT bidans_puskesmas_id_foreign FOREIGN KEY (puskesmas_id)
    REFERENCES public.puskesmas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bidans
    ADD CONSTRAINT bidans_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.jawaban_kuisioners
    ADD CONSTRAINT jawaban_kuisioners_kuisioner_id_foreign FOREIGN KEY (kuisioner_id)
    REFERENCES public.kuisioner_pasiens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.jawaban_kuisioners
    ADD CONSTRAINT jawaban_kuisioners_skrining_id_foreign FOREIGN KEY (skrining_id)
    REFERENCES public.skrinings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.kf
    ADD CONSTRAINT kf_id_anak_foreign FOREIGN KEY (id_anak)
    REFERENCES public.anak_pasien (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.kf
    ADD CONSTRAINT kf_id_nifas_foreign FOREIGN KEY (id_nifas)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.kf_kunjungans
    ADD CONSTRAINT kf_kunjungans_pasien_nifas_id_foreign FOREIGN KEY (pasien_nifas_id)
    REFERENCES public.pasien_nifas_rs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.kondisi_kesehatans
    ADD CONSTRAINT kondisi_kesehatans_skrining_id_foreign FOREIGN KEY (skrining_id)
    REFERENCES public.skrinings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pasien_nifas_bidan
    ADD CONSTRAINT pasien_nifas_bidan_bidan_id_foreign FOREIGN KEY (bidan_id)
    REFERENCES public.puskesmas (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pasien_nifas_bidan
    ADD CONSTRAINT pasien_nifas_bidan_pasien_id_foreign FOREIGN KEY (pasien_id)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pasien_nifas_rs
    ADD CONSTRAINT pasien_nifas_rs_kf1_id_foreign FOREIGN KEY (kf1_id)
    REFERENCES public.kf_kunjungans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pasien_nifas_rs
    ADD CONSTRAINT pasien_nifas_rs_kf2_id_foreign FOREIGN KEY (kf2_id)
    REFERENCES public.kf_kunjungans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pasien_nifas_rs
    ADD CONSTRAINT pasien_nifas_rs_kf3_id_foreign FOREIGN KEY (kf3_id)
    REFERENCES public.kf_kunjungans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pasien_nifas_rs
    ADD CONSTRAINT pasien_nifas_rs_pasien_id_foreign FOREIGN KEY (pasien_id)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pasien_nifas_rs
    ADD CONSTRAINT pasien_nifas_rs_rs_id_foreign FOREIGN KEY (rs_id)
    REFERENCES public.rumah_sakits (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pasiens
    ADD CONSTRAINT pasiens_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.puskesmas
    ADD CONSTRAINT puskesmas_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.resep_obats
    ADD CONSTRAINT resep_obats_riwayat_rujukan_id_foreign FOREIGN KEY (riwayat_rujukan_id)
    REFERENCES public.riwayat_rujukans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.resep_obats
    ADD CONSTRAINT resep_obats_rujukan_rs_id_foreign FOREIGN KEY (rujukan_rs_id)
    REFERENCES public.rujukan_rs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_kehamilan_gpas
    ADD CONSTRAINT riwayat_kehamilan_gpas_pasien_id_foreign FOREIGN KEY (pasien_id)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_kehamilan_gpas
    ADD CONSTRAINT riwayat_kehamilan_gpas_skrining_id_foreign FOREIGN KEY (skrining_id)
    REFERENCES public.skrinings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_kehamilans
    ADD CONSTRAINT riwayat_kehamilans_pasien_id_foreign FOREIGN KEY (pasien_id)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_kehamilans
    ADD CONSTRAINT riwayat_kehamilans_skrining_id_foreign FOREIGN KEY (skrining_id)
    REFERENCES public.skrinings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_penyakit_nifas
    ADD CONSTRAINT riwayat_penyakit_nifas_anak_pasien_id_foreign FOREIGN KEY (anak_pasien_id)
    REFERENCES public.anak_pasien (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_penyakit_nifas
    ADD CONSTRAINT riwayat_penyakit_nifas_nifas_id_foreign FOREIGN KEY (nifas_id)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_rujukans
    ADD CONSTRAINT riwayat_rujukans_rujukan_id_foreign FOREIGN KEY (rujukan_id)
    REFERENCES public.rujukan_rs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.riwayat_rujukans
    ADD CONSTRAINT riwayat_rujukans_skrining_id_foreign FOREIGN KEY (skrining_id)
    REFERENCES public.skrinings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rujukan_nifas
    ADD CONSTRAINT rujukan_nifas_id_kf_foreign FOREIGN KEY (id_kf)
    REFERENCES public.kf (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rujukan_nifas
    ADD CONSTRAINT rujukan_nifas_rs_id_foreign FOREIGN KEY (rs_id)
    REFERENCES public.rumah_sakits (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rujukan_rs
    ADD CONSTRAINT rujukan_rs_pasien_id_foreign FOREIGN KEY (pasien_id)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rujukan_rs
    ADD CONSTRAINT rujukan_rs_rs_id_foreign FOREIGN KEY (rs_id)
    REFERENCES public.rumah_sakits (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rujukan_rs
    ADD CONSTRAINT rujukan_rs_skrining_id_foreign FOREIGN KEY (skrining_id)
    REFERENCES public.skrinings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rumah_sakits
    ADD CONSTRAINT rumah_sakits_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.skrinings
    ADD CONSTRAINT skrinings_pasien_id_foreign FOREIGN KEY (pasien_id)
    REFERENCES public.pasiens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.skrinings
    ADD CONSTRAINT skrinings_puskesmas_id_foreign FOREIGN KEY (puskesmas_id)
    REFERENCES public.puskesmas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_role_id_foreign FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.wilayah_kerja
    ADD CONSTRAINT wilayah_kerja_puskesmas_id_foreign FOREIGN KEY (puskesmas_id)
    REFERENCES public.puskesmas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;